# Generated by Django 4.2.4 on 2024-05-06 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='romms',
            new_name='rooms',
        ),
    ]
