# Generated by Django 4.2.4 on 2024-05-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='vedio',
            name='file',
            field=models.URLField(),
        ),
    ]
